export const PLAYER_PALETTE = [
  { main: '#E11D48', light: '#FF8BA0', accent: '#FFBDC9' }, 
  { main: '#C026D3', light: '#F7A7FF', accent: '#FBD1FF' }, 
  { main: '#7C3AED', light: '#D2BDFF', accent: '#E9DFFF' }, 
  { main: '#2563EB', light: '#A5C9FF', accent: '#D1E3FF' }, 
  { main: '#0891B2', light: '#86EFFF', accent: '#C2F7FF' }, 
  { main: '#059669', light: '#8BF5CC', accent: '#C4FCE8' }, 
  { main: '#65A30D', light: '#D9FF9E', accent: '#EDFFD1' }, 
  { main: '#D97706', light: '#FFE08A', accent: '#FFF0C2' }, 
  { main: '#EA580C', light: '#FFC89E', accent: '#FFE4D1' }, 
  { main: '#4F46E5', light: '#BCC3FF', accent: '#DEE1FF' },
];

export const PROFILE_FRAMES = [
  { id: 'none', name: 'Default', price: 0, color: 'transparent' },
];

export const FLAGS = ['🇺🇸', '🇷🇺', '🇮🇷', '🇩🇪'];
export const LANGUAGES = ['en', 'ru', 'fa', 'de'];

export const TRANSLATIONS = {
  en: {
    arena: 'Arena',
    tasks: 'Tasks',
    rank: 'Rank',
    profile: 'Profile',
    shop: 'Shop',
    totalPool: 'Total Pool',
    startingIn: 'Starting in',
    players: 'Players',
    allIn: 'All-in',
    connectWallet: 'Connect Wallet',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    duckBalance: 'DUCK Balance',
    tonBalance: 'TON Balance',
    inviteFriends: "Invite friends and earn 10% of their spending TON",
    copy: 'Copy',
    share: 'Share',
    recentActivity: 'Recent Activity',
    topWin: 'Top Win',
    lastWin: 'Last Win',
    waiting: 'Waiting for Players...',
    taskCenter: 'Task Center',
    completeTasks: 'Complete tasks and Earn Rewards',
    daily: 'Daily',
    achievements: 'Achievements',
    partners: 'Partner',
    leaderboard: 'Leaderboard',
    top100: 'Top 100 Players by DUCK Volume',
    wins: 'Wins',
    comingSoon: 'Shop coming soon'
  },
  ru: {
    arena: 'Арена',
    tasks: 'Задания',
    rank: 'Ранг',
    profile: 'Профиль',
    shop: 'Магазин',
    totalPool: 'Общий пул',
    startingIn: 'Начало через',
    players: 'Игроки',
    allIn: 'Ва-банк',
    connectWallet: 'Подключить кошелек',
    deposit: 'Депозит',
    withdrawal: 'Вывод',
    duckBalance: 'Баланс DUCK',
    tonBalance: 'Баланс TON',
    inviteFriends: 'Приглашайте друзей и получайте 10% от их трат TON',
    copy: 'Копировать',
    share: 'Поделиться',
    recentActivity: 'Последние действия',
    topWin: 'Топ выигрыш',
    lastWin: 'Посл. выигрыш',
    waiting: 'Ожидание игроков...',
    taskCenter: 'Центр заданий',
    completeTasks: 'Выполняйте задания и получайте награды',
    daily: 'Ежедневно',
    achievements: 'Достижения',
    partners: 'Партнеры',
    leaderboard: 'Лидерборд',
    top100: 'Топ 100 игроков по объему DUCK',
    wins: 'Побед',
    comingSoon: 'Магазин скоро'
  },
  fa: {
    arena: 'میدان',
    tasks: 'وظایف',
    rank: 'رتبه',
    profile: 'پروفایل',
    shop: 'فروشگاه',
    totalPool: 'مجموع استخر',
    startingIn: 'شروع در',
    players: 'بازیکنان',
    allIn: 'همه موجودی',
    connectWallet: 'اتصال کیف پول',
    deposit: 'واریز',
    withdrawal: 'برداشت',
    duckBalance: 'موجودی DUCK',
    tonBalance: 'موجودی TON',
    inviteFriends: 'دوستان خود را دعوت کنید و ۱۰٪ از هزینه‌های TON آن‌ها را دریافت کنید',
    copy: 'کپی',
    share: 'اشتراک‌گذاری',
    recentActivity: 'فعالیت‌های اخیر',
    topWin: 'بیشترین برد',
    lastWin: 'آخرین برد',
    waiting: 'در انتظار بازیکنان...',
    taskCenter: 'مرکز وظایف',
    completeTasks: 'وظایف را انجام دهید و پاداش بگیرید',
    daily: 'روزانه',
    achievements: 'دستاوردها',
    partners: 'همکاران',
    leaderboard: 'جدول امتیازات',
    top100: '۱۰۰ بازیکن برتر بر اساس حجم DUCK',
    wins: 'بردها',
    comingSoon: 'فروشگاه به زودی'
  },
  de: {
    arena: 'Arena',
    tasks: 'Aufgaben',
    rank: 'Rang',
    profile: 'Profil',
    shop: 'Shop',
    totalPool: 'Gesamtpool',
    startingIn: 'Startet in',
    players: 'Spieler',
    allIn: 'All-in',
    connectWallet: 'Wallet verbinden',
    deposit: 'Einzahlung',
    withdrawal: 'Auszahlung',
    duckBalance: 'DUCK Guthaben',
    tonBalance: 'TON Guthaben',
    inviteFriends: 'Freunde einladen und 10% ihrer TON-Ausgaben verdienen',
    copy: 'Kopieren',
    share: 'Teilen',
    recentActivity: 'Letzte Aktivitäten',
    topWin: 'Top Gewinn',
    lastWin: 'Letzter Gewinn',
    waiting: 'Warten auf Spieler...',
    taskCenter: 'Aufgaben-Center',
    completeTasks: 'Aufgaben abschließen und Belohnungen verdienen',
    daily: 'Täglich',
    achievements: 'Erfolge',
    partners: 'Partner',
    leaderboard: 'Bestenliste',
    top100: 'Top 100 Spieler nach DUCK-Volumen',
    wins: 'Siege',
    comingSoon: 'Shop kommt bald'
  }
};

export const GUEST_DATA: any[] = [];

export const DEFAULT_AVATAR = "https://api.dicebear.com/7.x/identicon/svg?seed=User";
